spring:
  application:
    name: student-validation-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=student_validation
    username: postgres
    password: 3014
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# hook test